In [10]:
#Reshaping of arrays...
import numpy as np
A=np.array([[1,2,3,4,5,6,7,8]])
new_array=A.reshape(2,4)
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]


In [17]:
B=np.array([1,2,3,4])
A=np.array([2,3,4,6])
Sum=A+B
print(Sum)

[ 3  5  7 10]


In [31]:
A=np.array([[[[2,3],[4,5]]]])
B=np.array([[[[1,2],[3,7]]]])
C=np.concatenate([A,B],axis=0)
print(C)

[[[[2 3]
   [4 5]]]


 [[[1 2]
   [3 7]]]]


In [39]:
arr=np.array([[1,2],[2,3],[3,4],[5,6],[6,7],[7,8]])
new_array=np.array_split(arr,2.5)
print(new_array)

[array([[1, 2],
       [2, 3],
       [3, 4]]), array([[5, 6],
       [6, 7],
       [7, 8]])]


In [57]:
J=np.array([1,2,3,4,5,55,7,8,9])
x=np.sort(J)
y=x[::-1]
print(y)

[55  9  8  7  5  4  3  2  1]
